### ISSUE TITLE
Windows Blastn Error - System Exit Code 2

### ISSUE THREAD

**Issue by joelwebb** [flu-crew/octoFLU#16]
@tkanderson 
We are running Windows 10 Enterprise and attempted to set up OctoFlu by following your installation instructions. We have been running it successfully on a separate computer but on another, following the exact same instructions we ran into an error with blastn. 
![error](https://user-images.githubusercontent.com/25040566/74480908-64f3de80-4e77-11ea-93c4-00f233002e38.png)
Any ideas?

**Comment by tkanderson** [comment]
Hi Joel, are you able to execute the following from the directory where you have the reference.fa file? 

`makeblastdb -in reference.fa -dbtype nucl`

**Comment by joelwebb** [comment]
Thank you for the quick response; I am going to loop Jack Gallup in on this to see if he can run the aforementioned command. @JackmGallup - Can you test this out?

**Comment by j23414** [comment]
To provide more context:

`Error: mdb_env_open: There is not enough space on the disk`

may suggest a problem with `makeblastdb`. It seems to be a known issue with older versions of the program https://www.biostars.org/p/413294/ 

`makeblastdb -in reference.fa -dbtype nucl` 

may help us confirm/rule-out that possibility. If `makeblastdb` fails to generate a database, then `blastn` will fail to find the database.

**Comment by JackmGallup** [comment]
Hi All,  I did test this out - but got the same error:

Microsoft Windows [Version 10.0.17763.973]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data>makeblastdb -in reference.fa -dbtype nucl

Building a new DB, current time: 02/17/2020 10:11:23
New DB name:   C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data\reference.fa
New DB title:  reference.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data\reference.fa
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: There is not enough space on the disk.

C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data>

**Comment by JackmGallup** [comment]
Also, running as Administrator -- similar error:
C:\Data\Webb_2020\OctoFLU\octoFLU-master>makeblastdb -in reference.fa -dbtype nucl


Building a new DB, current time: 02/18/2020 07:38:03
New DB name:   C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference.fa
New DB title:  reference.fa
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
BLAST options error: File reference.fa does not exist

**Comment by JackmGallup** [comment]
Also this error when running cmd as Administrator from inside the correct folder:
Building a new DB, current time: 02/18/2020 07:42:38
New DB name:   C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data\reference.fa
New DB title:  reference.fa
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named C:\Data\Webb_2020\OctoFLU\octoFLU-master\reference_data\reference.fa
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: There is not enough space on the disk.

**Comment by j23414** [comment]
Ah, it does seem to be a `makeblastdb` issue... thanks for also checking if it was an admin permission issue!

You can also use `touch aa.txt` to try to create an `aa.txt` file which would fail either (1) if there's actually not enough space on disk (highly unlikely as I assume you have at least 3M of free disk space) or (2) if you lack permission to write a file to the `octoFLU-master\reference_data` folder.

I would recommend making sure your `makeblastdb` is the latest version (or update to latest version), and trying the solution at https://www.biostars.org/p/413294/. 

<img width="1002" alt="makeblastdb_error" src="https://user-images.githubusercontent.com/1077254/74742265-e48cff00-5223-11ea-84eb-51a472cec9b4.png">

They mention setting an environmental variable `BLASTDB_LMDB_MAP_SIZE=1000000` (notice in your output, `Maximum file size: 1000000000B`)

Instructions for changing the windows environmental variables are at https://www.ncbi.nlm.nih.gov/books/NBK52637/

<img width="1025" alt="Env_var" src="https://user-images.githubusercontent.com/1077254/74743796-a93fff80-5226-11ea-9150-11853e3912a2.png">

**Comment by JackmGallup** [comment]
Jen can you join Joe and I on Skype?

**Comment by j23414** [comment]
Sure thing, my skype username is `jen.chang.212`. I'll delete the username later today

**Comment by JackmGallup** [comment]
Hi Jen

We are here:

Jack
.........................................................................................................................................
Join Skype Meeting<https://lync.boehringer-ingelheim.com/boehringer-ingelheim.com/meet/jack.gallup/STDNPW24>
Trouble Joining? Try Skype Web App<https://lync.boehringer-ingelheim.com/boehringer-ingelheim.com/meet/jack.gallup/STDNPW24?sl=1>
Join by phone

+1 203 778 7979 English (United States - Ridgefield)<tel:+1%20203%20778%207979%20English%20(United%20States%20-%20Ridgefield)> (North America - USA - Worthington)                               English (United States)
+1 203 798 5000  English (United States - Ridgefield)<tel:+1%20203%20798%205000%20%20English%20(United%20States%20-%20Ridgefield)> (North America - USA - Worthington)                              English (United States)

Find a local number<https://lync.boehringer-ingelheim.com/dialin>

Conference ID: 371879817
 Forgot your dial-in PIN?<https://lync.boehringer-ingelheim.com/dialin> |Help<http://skype>

[!OC([1033])!]
.........................................................................................................................................

**Comment by joelwebb** [comment]
Thank you for our help and this solved the issue!

**Comment by j23414** [comment]
Sure thing! : )
